format_version: 10

pipelines:
  HelloWorldPipeline:
    group: Test
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/htetgit/hello-world.git
        branch: master
        username: htetgit
        password: "{{GITHUB_PAT}}"   # Secure reference to GitHub Personal Access Token
    stages:
      - Build:
          jobs:
            BuildJob:
              tasks:
                # Build Go app
                - exec:
                    command: go
                    arguments:
                      - build
                      - -o
                      - main
                      - main.go
                # Run Go tests
                - exec:
                    command: go
                    arguments:
                      - test
                      - ./...
      - Test:
          jobs:
            TestJob:
              tasks:
                # Run Python test script
                - exec:
                    command: python3
                    arguments:
                      - python.py
      - Deploy:
          jobs:
            DeployJob:
              tasks:
                # Simulated deploy step
                - exec:
                    command: echo
                    arguments:
                      - "Deploying application..."
