format_version: 10

pipelines:
  HelloWorld:
    group: Test
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/htetgit/hello-world.git
        branch: master
        username: htetgit
        password: "{{GITHUB_PAT}}"   # Secure reference
    stages:
      - Build:
          jobs:
            BuildJob:
              tasks:
                - script: echo "Hello World from GoCD"
